---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: ubuntu1204
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: fedora27

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
